### ISSUE TITLE
You have a bugbot on your hands

### ISSUE THREAD

**Issue by ericbarefoot** [amoodie/pull-request-bot#1]
@amoodie, someone has hacked your machine and inserted a spambot. Might want to increase security... Please find the offensive email below. From: pull-request-bot@andrewjmoodie.com<br>
Subject: You have unreviewed open pull requests<br>
First Attachment: https://ift.tt/19fNRe4<br>
Date: March 27, 2018 at 05:57PM<br>
<br>
Hello <tt>ericbarefoot</tt>,<br>
<br>
It has come to our attention that a repository you own:<br>
<p style="text-indent: 40px;"><tt>compact_proposal</tt></p>
has open pull requests created by user:<br>
<p style="text-indent: 40px;"><tt>amoodie</tt></p>
<br>
The oldest of the pull requests was opened on March 5; that's 22 days ago! Please log on to GitHub and review any open pull requests.<br>
<br>
Some information about any open requests is below:<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
This email was generated by a script and does not respond well to being threatened.<br>
You can view the source code on <a href="https://github.com/amoodie/pull-request-bot">GitHub</a>.<br>
<br>
<br>
via Gmail
<table style="width: 50%;">
<tr>
<th>Pull Request Title</th>
<th>Created on</th>
<th>Author</th>
</tr>
<tr>
<td>Feat hdrprinting</td>
<td>March 22</td>
<td>amoodie</td>
</tr>
<tr>
<td>implement font handler with etoolbox and kvoptions</td>
<td>March 5</td>
<td>amoodie</td>
</tr>
</table>

**Comment by amoodie** [comment]
Thanks, but this is a feature, not a bug.
